FROM python:alpine AS build-env
WORKDIR /root
COPY requirements.txt /root
RUN apk update && apk add \
    g++ \
    gcc \
    libffi-dev \
    openssl-dev \
    tzdata \
    && cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime \
    && echo "Asia/Tokyo" > /etc/timezone \
    && python3 -m pip install -r requirements.txt


FROM python:alpine
WORKDIR /app
COPY --from=build-env /etc/localtime /etc/localtime
COPY --from=build-env /etc/timezone /etc/timezone
COPY --from=build-env /usr/local/bin /usr/local/bin
COPY --from=build-env /usr/local/lib/python3.7/site-packages /usr/local/lib/python3.7/site-packages
COPY . /app
RUN find . -type f -exec chmod -x {} \;
# Update & Install Requirments Packages.
RUN apk update && apk add \
    bash \
    git \
    && rm -rf /var/cache/apk/* \
    && errbot --init

# Run
CMD ["bash", "run.sh"]
