version: '2.1'

services:
  errbot:
    image: winuim/errbot
    build: 
      context: .
    environment:
      - BACKEND=Slack
      - BOT_ADMINS=@winuim
      - ERRBOT_SLACK_TOKEN
    stdin_open: true
    tty: true
