version: '2.1'

services:
  errbot:
    image: winuim/errbot
    build: 
      context: .
    environment:
      - BACKEND=Slack
      - BOT_LOG_LEVEL=DEBUG
      - BOT_SLACK_TOKEN
      - BOT_ADMINS=@winuim
      - BOT_ALT_PREFIXES=@errbot
    stdin_open: true
    tty: true
